---
title: "Tango-cc analysis"
author: "Julia Prein"
date: "10/27/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse) # data handling etc.
library(tidybayes) # for stat_halfeye, add_predictive_draws
library(tidyboot) # for bootstrapped CIs
library(brms) # modeling
library(cmdstanr) # modeling
library(janitor) # clean_names
library(ggpubr) # ggarrange
library(splithalfr) # split half reliability
library(ggridges) # for ridge plot
library(RColorBrewer) # for color palette
library(pals) # for color palette
library(Hmisc) # for kelly color palette
# load source code for geom_flat_violin()
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")

options(scipen = 999) # turn off scientific notation
theme_set(theme_classic()) # set theme

# Seed for random number generation
set.seed(42)

# color palette
# qual_col_pals = brewer.pal.info[brewer.pal.info$colorblind == TRUE,]
# col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
# 
# # kelly palette of 22 colors maximize the contrast between colors in a set if the colors are chosen in sequential order. Kelly paid attention to the needs of people with color blindness
# colors=kelly(n=n_distinct(data$community) +1)

# create a custom color pallette with 17 easily distinguishable, different colors
custom_palette <- c(
  brewer.pal(11, "RdYlGn"),
  brewer.pal(6, "BuPu")
)
```

```{r load_data}
complete_data <- read_csv("../data/data.csv")
```

```{r data_preparation}
# complete dataset, with all trials
all_trials <- complete_data %>% 
    mutate(continent = ifelse(
    community %in% c("leipzig", "plymouth"), "Europe", 
    ifelse(
      community %in% c("akure", "hai||om", "khwe", "chimfunshi", "bandongo", "bayaka", "windhoek", "uganda"), "Africa",
      ifelse(community %in% c("stanford", "mexico", "buenos_aires"), "Americas",
             ifelse(community %in% c("india", "beijing", "turkey"), "Asia", "Oceania"))
    )
  )) %>%
  mutate(continent = factor(continent, levels = c("Americas", "Africa", "Europe", "Asia", "Oceania"), ordered = T)) %>%
  mutate(community = recode(community,
                            akure = "Akure (Nigeria)",
                            leipzig = "Leipzig (Germany)",
                            `hai||om` = "Hai||om (Namibia)",
                            khwe = "Khwe (Namibia)",
                            windhoek = "Windhoek (Namibia)",
                            stanford = "Stanford (USA)",
                            chimfunshi = "Chimfunshi (Zambia)",
                            mexico = "Ocuilan (Mexico)",
                            plymouth = "Plymouth (UK)",
                            beijing = "Beijing (China)", 
                            india = "Pune (India)",
                            buenos_aires = "Buenos Aires (Argentina)",
                            auckland = "Auckland (New Zealand)",
                            turkey = "Malatya (Türkiye)",
                            bandongo = "Bandongo (Rep. Congo)",
                            bayaka = "BaYaka (Rep. Congo)", 
                            uganda = "Nyabyeya (Uganda)")
  ) %>% 
  mutate(
    imprecision = abs(clickdistfromtargetcenterx)/160,
    centrality = as.character(abs(5-targetposition))
  )

# dataset with test trials only 
data <- all_trials %>%
  filter(trialtype == "test", voiceover == F) %>%
  mutate(trialnr = as.numeric(factor(trialnr))) 

# dataset with test trials only, with mean imprecision per participant
# scale age across communities; mean_imprecision per subjid; household, touchscreen scaled per community
mdata <- data %>%
  mutate(age = scale(ageinyears, center = T, scale = F)) %>%
  group_by(subjid, community, age_group, ageinyears, age, household, touchscreen) %>%
  summarise(mean_imprecision = mean(imprecision)) %>%
  group_by(community) %>%
  mutate(
    household = scale(household), 
    touchscreen = factor(touchscreen),
  ) %>%
  na.omit()
```

```{r sample}
# full sample
all_trials %>%
  group_by(subjid) %>%
  summarise(n= n()) %>%
  arrange(n)

all_trials %>%
  group_by(community, age_group) %>%
  summarise(n= n_distinct(subjid))

all_trials %>%
  group_by(community) %>%
  summarise(n= n_distinct(subjid))

all_trials %>%
  summarise(n= n_distinct(subjid))

# model data
mdata %>%
  group_by(community, age_group) %>%
  summarise(n= n_distinct(subjid))

mdata %>%
  group_by(community) %>%
  summarise(n= n_distinct(subjid))

mdata %>% ungroup() %>% 
  summarise(n= n_distinct(subjid))
```

```{r exclude_children}
# children who did not finish all trials are removed (only 5 children total)
exclude <- all_trials %>%
  filter(trialtype == "test", voiceover == F) %>%
  group_by(subjid) %>%
  summarise(n= n()) %>%
  filter(n < 15) %>%
  pull(subjid)

all_trials <- all_trials %>% filter(!subjid %in% exclude)
data <- data %>% filter(!subjid %in% exclude)
mdata <- mdata %>% filter(!subjid %in% exclude)
```

```{r samplesize_plot}
data %>% 
  summarise(click = mean(imprecision), .by = c(community, ageinyears)) %>%
  ggplot(mapping = aes(x = community, 
                     y = ageinyears, 
                     fill = community)) + 
  geom_flat_violin(scale = "count", trim = T) + 
  geom_dotplot(binaxis = "y",
               dotsize = 1,
               stackdir = "down",
               binwidth = 0.1,
               position = position_nudge(-0.025)) +
  guides(fill = "none") +
  scale_y_continuous(limits = c(2, 11), breaks = seq(2, 11, 1)) + 
  labs(x = "", y = "Age in years") + 
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) + 
  scale_fill_manual(values = custom_palette)

ggsave("../figures/age_distribution.png", width = 10, height = 5, scale = 1.1)
```

# Variation

```{r scatterplot}
mdata %>% 
  ggplot() +
  geom_point(aes(x = ageinyears, y = mean_imprecision, col = community), alpha = 0.9) +
  scale_color_manual(values = custom_palette) +
  scale_x_continuous(limits = c(2, 11), breaks = seq(2, 11, 1)) +
  scale_y_continuous(limits = c(0, 7), breaks = seq(0, 7, 1)) +
  labs(x = "Age in years", y = "Average absolute imprecision in target width", col = "")

ggsave("../figures/age_imprecision.png", width = 8, height = 5, scale = 1)
```

```{r ind_diff}
mdata %>% 
  ggplot(aes(x = community, y = mean_imprecision, col = ageinyears)) +
  geom_jitter(width = 0.2, height = 0.2, size = 0.9, alpha = 0.9) +
  scale_color_viridis_c(direction = -1) +
  scale_y_continuous(limits = c(0, 7), breaks = seq(0, 7, 1)) +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1), 
    plot.margin = margin(l = 25)
  ) +
  labs(x = "", y = "Average absolute imprecision in target width", col = "Age in years")

ggsave("../figures/ind_diff.png", width = 8, height = 5, scale = 1)
```

```{r training_trials}
# function to suppress labels
delete_no_display <- function(v) {
  if_else(str_detect(v, 'no_display'), '', v)
}

all_trials %>% 
  mutate(trialtype = recode(trialtype, touch = "Training 1", fam = "Training 2", test = "Test") %>% as_factor(.)) %>%
  na.omit() %>%
  summarise(mean_click = mean(imprecision), .by = c(continent, community, subjid, ageinyears, trialtype)) %>% 
  mutate(
    continent = fct_inorder(continent) %>% fct_rev(.), 
    # so that first facet row doesnt show x axis labels
    trialtype = if_else(continent == "Africa",
                              as.character(trialtype),
                              paste0(as.character(trialtype), 'no_display')) %>% as_factor(.) %>% fct_relevel(., "Training 1", "Training 2", "Test")
  ) %>%
  ggplot(aes(x = trialtype, y = mean_click, col = ageinyears)) +
  geom_jitter(width = 0.2, size = 0.9, alpha = 0.9) +
  scale_color_viridis_c(direction = -1) +
  scale_y_continuous(limits = c(0, 7), breaks = seq(0, 7, 1)) +
  theme_light() +
  facet_wrap(~ continent * community, nrow = 2, scales="free_x") +
    theme(
    axis.text.x = element_text(angle = 30, hjust = 1), 
    legend.position = c(0.95, 0.25), 
    axis.ticks.x = element_blank(),
  ) +
  scale_x_discrete(label = delete_no_display) +
  labs(x = "", y = "Average absolute imprecision in target width", col = "Age in years")

ggsave("../figures/training_trials.png", width = 11, height = 5, scale = 1.3)
```

```{r sd_plot}
sd_df <- data %>% 
  add_row(community = "OVERALL") %>% 
  summarise(
    mean_ind = mean(imprecision),
    sd_ind = sd(imprecision), 
    .by = c(community, subjid, ageinyears)
  ) %>%
  mutate(
    mean_community = mean(mean_ind, na.rm = TRUE),
    sd_community = sd(mean_ind, na.rm = TRUE),
    .by = community
  ) %>%
  mutate(sd_overall = sd(mean_community, na.rm = TRUE), facet = ifelse(community == "OVERALL", "OVERALL", "COMMUNITY"))

# plot sd of individual and community means
sd_df %>% 
  ggplot() +
  geom_jitter(data = sd_df %>%  filter(facet == "COMMUNITY"), aes(x = community, y = sd_ind, col = ageinyears), width = 0.1, size = 0.9, alpha = 0.5) +
  geom_point(data = sd_df %>%  filter(facet == "COMMUNITY"), aes(x = community, y = sd_community), size = 3, pch = 18) +
  geom_point(data = sd_df %>%  filter(facet == "OVERALL"), aes(x = "OVERALL", y = sd_overall), size = 5, pch = 18, color = "purple") +
  facet_grid(~ facet, scales = "free", space = "free") +
  scale_color_viridis_c(direction = -1) +
  scale_y_continuous(limits = c(0, 4), breaks = seq(0, 4, 1)) +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1), 
    plot.margin = margin(l = 25), 
    strip.text = element_blank()
  ) +
  labs(x = "", y = "Standard deviation of clicks", col = "Age in years")

ggsave("../figures/sd_plot.png", width = 10, height = 5, scale = 1)
```

# Dev Model 

```{r models}
# age scaled across communities; touchscreen factor, household scaled per community
# full_model <- brm(mean_imprecision ~ age + touchscreen + household + (age + touchscreen + household | community),
#                 data   = mdata,
#                 family = lognormal(),
#                 warmup = 1000,
#                 iter   = 3000,
#                 control = list(adapt_delta = 0.95),
#                 chains = 4,
#                 cores  = 4) %>% 
#   add_criterion(., c("waic","loo"))
# 
# saveRDS(full_model, "../saves/full_model.rds")

full_model <- readRDS("../saves/full_model.rds")

# only age
# age_model <- brm(mean_imprecision ~ age + (age | community),
#                 data   = mdata,
#                 family = lognormal(),
#                 warmup = 1000,
#                 iter   = 3000,
#                 control = list(adapt_delta = 0.95),
#                 chains = 4,
#                 cores  = 4) %>% 
#   add_criterion(., c("waic","loo"))
# 
# saveRDS(age_model, "../saves/age_model.rds")

age_model <- readRDS("../saves/age_model.rds")
```

```{r model_comparison}
```

```{r age_model_plot}
ndata <- mdata %>%
  distinct(community) %>%
  expand_grid(age = unique(mdata$age))

post <- fitted(age_model, newdata = ndata, re_formula = ~ (age | community)) %>%
  as_tibble() %>%
  bind_cols(ndata) %>%
  # because we scaled age beforehand, we need to add the mean age back in
  mutate(age = age + mean(mdata$ageinyears))

ggplot() +
  geom_smooth(data = post, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = community, col = community), alpha = .25, stat = "identity") +
  geom_point(data = mdata, aes(x = (age + mean(mdata$ageinyears)), y = mean_imprecision, col = community), pch = 19, alpha = 0.5) +
  scale_x_continuous(limits = c(2, 11), breaks = seq(2, 11, 1)) +
  scale_y_continuous(limits = c(0, 7), breaks = seq(0, 7, 1)) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = "Age in years", y = "Average imprecision in target width", fill = "", col = "")

ggsave("../figures/age_model.png", width = 8, height = 5, scale = 1)
```

```{r posterior_samples}
ps <- full_model %>% posterior_samples() %>%
  select("b_Intercept", "b_age", "b_household", "b_touchscreen1", starts_with("r_community")) %>% 
  pivot_longer(cols = c(5:72), names_to = "community", values_to = "value") %>%
  mutate(
         community = str_remove(community, "r_community"),
         community = str_remove(community, "\\]"), 
         community = str_remove(community, "\\["), 
         ) %>%
  separate(col = community, into = c("community", "parameter"), sep = ",") %>% 
  pivot_longer(cols = c(b_Intercept, b_household, b_age, b_touchscreen1), names_to = "fix_param", values_to = "fix_value") %>%
  mutate(fix_param = tolower(str_remove(fix_param,"b_")), 
         parameter = tolower(parameter), 
         fix_param = str_remove(fix_param, "1"), 
         parameter = str_remove(parameter, "1"), 
         community = str_replace(community, "\\.", " "), 
         community = factor(community) %>% 
           recode(., 
                  `Auckland (New.Zealand)` = "Auckland (New Zealand)", 
                  `Bandongo (Rep..Congo)` = "Bandongo (Rep. Congo)",
                  `BaYaka (Rep..Congo)` = "BaYaka (Rep. Congo)"
                  )
  ) %>%
  filter(parameter == fix_param) %>%
  mutate(est = value + fix_value)
```

```{r age_estimates}
ps %>% 
  filter(parameter == "age") %>%
  ggplot(aes(y = fct_rev(community), x = est, fill = stat(x) > 0)) +
  tidybayes::stat_halfeye(alpha = .8, .width = c(.95, .80), scale = 1) +
    labs(x = "Age - posterior estimate", y ="") +
  guides(fill = "none") +
  geom_vline(xintercept = fixef(full_model) %>% as_tibble(rownames = "param") %>% filter(param == "age") %>% pull(Estimate), linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "solid") +
  scale_fill_manual(values = c("#29485D", "grey")) +
  theme_minimal()
```

# Demographics 

```{r demographics_descriptives}
demographics <- data %>%
  mutate(older_children = children - 1 - younger_children) %>%
  group_by(community)%>%
  summarise(screen = mean(screen, na.rm = T),
            touchscreen = mean(touchscreen, na.rm = T), 
            older_children = mean(older_children, na.rm = T), 
            household = mean(household, na.rm = T))%>%
  pivot_longer(names_to = "predictor", values_to = "value", cols = c(screen, touchscreen, older_children, household))

demographics


```

```{r touchscreen}
touchscreen_model <- ps %>% 
  filter(parameter == "touchscreen") %>%
  ggplot(., aes(x = est, y = fct_rev(community))) +
  geom_vline(xintercept = 0, lty = "solid", color = "black", size = 0.5) +
  geom_point(size = 0.5, alpha = .5) +
  geom_density_ridges(col = "white", alpha = .5, rel_min_height = 0.01, fill="#29485D") +
  scale_x_continuous(limits = c(-1, 0.5), breaks = seq(-1, 0.5, 0.25)) +
  theme_light() + 
  labs(x = "Posterior estimate", y = "")

touchscreen_model

ggsave("../figures/touchscreen_model.png", width = 5, height = 5, scale = 0.9, bg = "white")

touchscreen_descr <- demographics %>% 
  filter(predictor == "touchscreen") %>%
  ggplot(aes(x = predictor, y = fct_rev(community), fill = value)) +
  geom_point(pch = 22, size = 5, stroke = 0) +
  scale_fill_viridis_c() +
  labs(x = "", y = "", fill = "Proportion") +
  theme(axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
  )

touchscreen_descr

ggsave("../figures/touchscreen_descr.png", width = 3.5, height = 5, scale = 0.9, bg = "white")
```



```{r household}
household_model <- ps %>% 
  filter(parameter == "household") %>%
  ggplot(., aes(x = est, y = fct_rev(community))) +
  geom_vline(xintercept = 0, lty = "solid", color = "black", size = 0.5) +
  geom_point(size = 0.5, alpha = .5) +
  geom_density_ridges(col = "white", alpha = .5, rel_min_height = 0.01, fill="#29485D") +
  scale_x_continuous(limits = c(-0.25, 0.25), breaks = seq(-0.25, 0.25, 0.125)) +
  theme_light() + 
  labs(x = "Posterior estimate", y = "")

household_model

ggsave("../figures/household_model.png", width = 5, height = 5, scale = 0.9, bg = "white")

household_descr <- demographics %>% 
  filter(predictor == "household") %>%
  ggplot(aes(x = predictor, y = fct_rev(community), fill = value)) +
  geom_point(pch = 22, size = 5, stroke = 0) +
  scale_fill_viridis_c() +
  labs(x = "", y = "", fill = "# Members") +
  theme(axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
  )

household_descr

ggsave("../figures/household_descr.png", width = 3.5, height = 5, scale = 0.9, bg = "white")
```

# Gaze model U

```{r u_plot}
clicks_bin <- data %>%
  mutate(targetposition = factor(targetposition, levels = c(1:10))) %>%
  group_by(community, targetposition) %>%
  tidyboot_mean(column = imprecision)

clicks_bin %>% 
  ggplot(aes(x = targetposition, y = mean, col = community)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), pch = 20, alpha = 1, position = position_dodge(width = .5)) +
  labs(x = "Target position (binned)", y = "Average absolute imprecision in target width", col = "") +
  scale_y_continuous(limits = c(0, 7), breaks = seq(0, 7, 1)) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette)

ggsave("../figures/target_position.png", width = 8, height = 4, scale = 1.1)
```

# Internal Consistency
## Odd-even

```{r odd_even_plot}
odd_even <- data %>%
  mutate(half = ifelse(trialnr %% 2 == 0, "half_1", "half_2")) %>%
  group_by(subjid, community, half) %>%
  summarise(mean_imprecision = mean(imprecision)) %>%
  pivot_wider(names_from = half, values_from = mean_imprecision) %>%
  group_by(community) %>%
  summarise(reli = cor(half_1, half_2)) %>%
  ggplot(aes(x = reli, y = fct_rev(community))) +
  geom_vline(xintercept = 0, lty = 3, alpha = .75) +
  geom_point(alpha = .5) +
  scale_x_continuous(limits = c(-0.5, 1), breaks = c(-0.5, 0, 0.5, 0.6,0.7, 0.8, 0.9, 1)) +
  labs(x = "Simple odd-even split", y = "") +
  theme_light() +
  theme(axis.title.x = element_text(size = 10))

odd_even
```


## Stratified by target position (categorical target centrality)

```{r stratified_data}
# fn_mean <- function(ds) {
#   return(mean(abs(ds$clickdistfromtargetcenterx), na.rm = TRUE))
# }
# 
# rel <- tibble()
# 
# communities <- unique(data$community)
# 
# for (j in c(1:50)) {
#   for (i in communities) {
#     # stratified by target position
#     rel_s <- by_split(
#       data = data %>% filter(community == i),
#       participants = data %>% filter(community == i) %>% pull(subjid),
#       fn_score = fn_mean,
#       verbose = F,
#       stratification = paste(data %>% filter(community == i) %>% pull(centrality)),
#       careful = FALSE
#       )
#     
#     samp <- tibble(
#       community = i,
#       iter = j,
#       reli = split_coefs(rel_s, cor),
#       lci = split_ci(rel_s, cor)$lims["0.025","bca"],
#       uci = split_ci(rel_s, cor)$lims["0.975","bca"]
#       )
#     
#     print(i)
#     print(j)
#     print(rel_s)
#     print(samp)
#     
#     rel <- bind_rows(rel, samp)
#   }
# }

# saveRDS(rel, "../saves/stratified_internal_consistency.rds")

rel <- readRDS("../saves/stratified_internal_consistency.rds")
```

```{r stratified_plot}
stratified_plot <- rel %>%   
  ggplot(., aes(x = reli, y = fct_rev(community))) +
  geom_vline(xintercept = 0, lty = 3, alpha = .75) +
  geom_point(alpha = .5) +
  geom_density_ridges(col = "white", alpha = .5, rel_min_height = 0.01, fill="#29485D") +
  scale_x_continuous(limits = c(-0.5, 1), breaks = c(-0.5, 0, 0.5, 0.6,0.7, 0.8, 0.9, 1)) +
  theme_light() +
  labs(y = "", x = "Stratified by target centrality") +
  theme(axis.title.x = element_text(size = 10))

stratified_plot

ggsave("../figures/splithalf_stratified.png", width = 8, height = 5, scale = 1, bg = "white")
```

## Stratified and age-corrected

```{r stratified_agecorrected_data}
# estimate age-corrected reliability
# run model first for one community to use update()
# split <- split_df(
#   data = data %>% filter(community == "Leipzig (Germany)"),
#   stratification = data %>% filter(community == "Leipzig (Germany)") %>% pull(centrality),
#   careful = FALSE
# )
# 
# sdata <- bind_rows(
#   split[[1]] %>% 
#     select(subjid, ageinyears, clickdistfromtargetcenterx) %>% 
#     mutate(impr = abs(clickdistfromtargetcenterx), half = "half_1"),
#   split[[2]] %>% 
#     select(subjid, ageinyears, clickdistfromtargetcenterx) %>%
#     mutate(impr = abs(clickdistfromtargetcenterx), half = "half_2")) %>%
#   mutate(age = scale(ageinyears))
# 
# reli_age <- brm(impr ~ age + (0 + half | subjid),
#                 data   = sdata,
#                 family = lognormal(),
#                 warmup = 1000,
#                 iter   = 3000,
#                 control = list(adapt_delta = 0.95),
#                 chains = 4,
#                 cores  = 4)
# 
# # loop over communities
# communities <- unique(data$community)
# 
# model_cor <- tibble()
# 
# for (j in c(1:50)) {
#   for (i in communities) {
#     
#     com_split <- split_df(
#       data = data %>% filter(community == i),
#       stratification = data %>% filter(community == i) %>% pull(centrality),
#       careful = FALSE
#     )
#     
#     com_sdata <- bind_rows(
#       com_split[[1]] %>% 
#         select(subjid, ageinyears, clickdistfromtargetcenterx) %>%
#         mutate(impr = abs(clickdistfromtargetcenterx), half = "half_1"),
#       com_split[[2]] %>%
#         select(subjid, ageinyears, clickdistfromtargetcenterx) %>%
#         mutate(impr = abs(clickdistfromtargetcenterx), half = "half_2")) %>%
#       mutate(age = scale(ageinyears))
#     
#     com_mod <- update(reli_age,
#         newdata = com_sdata,
#         warmup = 1000,
#         iter   = 3000,
#         control = list(adapt_delta = 0.95),
#         chains = 4,
#         cores  = 4)
#     
#     cor <- summary(com_mod)$random$subjid %>%
#       as_tibble(rownames = "parameter") %>%
#       filter(parameter == "cor(halfhalf_1, halfhalf_2)") %>%
#       mutate(community = i, iter = j)
#     
#     model_cor <- bind_rows(model_cor, cor)
#   }
# }
# 
# saveRDS(model_cor, "../saves/age_corrected_internal_consistency.rds")

model_cor <- readRDS("../saves/age_corrected_internal_consistency.rds")
```

```{r stratified_agecorrected_plot}
stratified_agecorrected_plot <- model_cor %>% 
  ggplot(., aes(x = Estimate, y = fct_rev(community))) +
  geom_vline(xintercept = 0, lty = 3, alpha = .75) +
  geom_point(alpha = .5) +
  geom_density_ridges(col = "white", alpha = .5, rel_min_height = 0.01, fill="#29485D") +
  scale_x_continuous(limits = c(-0.5, 1), breaks = c(-0.5, 0, 0.5, 0.6, 0.7, 0.8, 0.9, 1)) +
  theme_light() +
  labs(y = "", x = "Stratified by target centrality, model-based age correction") +
  theme(axis.title.x = element_text(size = 10))

stratified_agecorrected_plot

ggsave("../figures/splithalf_stratified_agecorrected.png", width = 8, height = 5, scale = 1, bg = "white")
```

```{r consistency_plots}
ggarrange(
  odd_even,
  stratified_plot + theme(axis.text.y = element_blank(), axis.ticks.y=element_blank()), 
  stratified_agecorrected_plot + theme(axis.text.y = element_blank(), axis.ticks.y=element_blank()), 
  widths = c(2, 1.5, 1.5), 
  nrow = 1,
  labels = "AUTO" 
)

ggsave("../figures/splithalf.png", width = 14, height = 5, scale = 0.9, bg = "white")
```
